#!/usr/bin/env node
/**
 * Builds and publishes the landing page to Vercel.
 *
 * Vercel serves `landing/` with no build step of its own — `vercel.json`
 * sets an empty `buildCommand` and `outputDirectory: "landing"` — so
 * what is uploaded is exactly what is committed. That means the CSS and
 * HTML have to be built here, before the upload, or the deploy silently
 * ships whatever was built last.
 *
 * There is no git integration on the project: `vercel git connect` has
 * never been run, so a push does not deploy and this script is the only
 * thing that publishes. That is worth knowing rather than discovering,
 * because the site sat several commits behind for most of a day looking
 * perfectly healthy.
 *
 * `binary.json` is not built here. It is generated by the release
 * workflow, attached to the release, and committed by hand — so a
 * deploy publishes whatever version is committed, which is the point:
 * the site should advertise the release that exists, not the version
 * the working tree happens to be on.
 *
 *   npm run landing:deploy
 */
import { execFileSync } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

// `shell: true` on Windows: Node refuses to spawn a .cmd directly, and
// both npm and npx are .cmd shims there.
const shell = process.platform === 'win32'
const npx = shell ? 'npx.cmd' : 'npx'
const npm = shell ? 'npm.cmd' : 'npm'

console.log('Building the landing page…')
execFileSync(npm, ['run', 'landing:build'], { cwd: ROOT, stdio: 'inherit', shell })

console.log('\nDeploying to production…')
// `--yes` so a linked project does not stop to ask what it already
// knows from .vercel/project.json.
const out = execFileSync(npx, ['--yes', 'vercel@latest', '--prod', '--yes'], {
  cwd: ROOT,
  encoding: 'utf-8',
  shell,
  stdio: ['inherit', 'pipe', 'inherit'],
})

// The CLI prints the deployment URL on stdout; the last one is the
// production alias.
const url = out.trim().split('\n').filter(l => l.startsWith('https://')).pop()
console.log(`\n  ${url ?? out.trim()}`)
console.log('\n  Verify what actually went live, not that the command exited 0:')
console.log('    curl -s https://cernix.app/binary.json | head -3')
console.log('  The version there is what the download buttons will hand out.')
